[package]
org = "wso2"
name = "mi"
version = "0.4.0"
authors = ["Ballerina"]
keywords = ["wso2-mi"]
repository = "https://github.com/wso2-extensions/ballerina-module-wso2-mi.git"
license = ["Apache-2.0"]
distribution = "2201.12.0"
export = ["mi"]
