[plugin]
class = "io.ballerina.stdlib.mi.plugin.MICompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/mi-compiler-plugin-0.4.0.jar"

[[dependency]]
path = "build/antlr4-runtime-4.7.1.jar"

[[dependency]]
path = "build/handlebars-4.0.6.jar"
