name: Publish Release

on:
  workflow_dispatch:
  repository_dispatch:
    types: [stdlib-release-pipeline]

jobs:
  call_workflow:
    name: Run Release Workflow
    if: ${{ github.repository_owner == 'wso2-extensions' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/release-package-template.yml@main
    secrets: inherit
    with:
      package-name: mi
      package-org: wso2
